chatapp/urls.py
from django.urls import path
from . import views

app_name = 'chatapp'
urlpatterns = [
    path('',views.Login,name='login'),
    path("logout",views.Logout,name="Logout"),
    path('register', views.AccountRegistration.as_view(), name='register'),
    path('home', views.home, name='home'),
    path('message/<int:num>', views.message, name='message'),
    path('setting/<int:num>', views.setting, name='setting'),
    path('namechange/<int:num>', views.namechange, name='namechange'),
    path('adresschange/<int:num>', views.adresschange, name='adresschange'),
    path('iconchange/<int:num>', views.iconchange, name='iconchange'),
    path('password/<int:num>', views.password, name='password'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chatapp/', include('chatapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.Login.as_view(), name="login"),
    path("friends/", views.friends, name="friends"),
    # トーク画面
    # 誰とのトークかを、URLにて判別
    # ユーザー名に重複が許されていないので、ユーザー名で判別
    path("talk_room/<int:user_id>/", views.talk_room, name="talk_room"),
    path("setting/", views.setting, name="setting"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("password_change/", views.PasswordChange.as_view(), name="password_change"),
    path(
        "password_change_done/",
        views.PasswordChangeDone.as_view(),
        name="password_change_done",
    ),
    path("user_img_change/", views.user_img_change, name="user_img_change"),
    path(
        "user_img_change_done/", views.user_img_change_done, name="user_img_change_done"
    ),
    path("mail_change/", views.mail_change, name="mail_change"),
    path("mail_change_done/", views.mail_change_done, name="mail_change_done"),
    path("username_change/", views.username_change, name="username_change"),
    path(
        "username_change_done/", views.username_change_done, name="username_change_done"
    ),
]

chatapp/models.py
from django.db import models
#ユーザー認証
from django.contrib.auth.models import User

#ユーザーアカウントのモデルクラス
class Account(models.Model):
    #ユーザーアカウントのモデルクラス
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #追加フィールド
    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    account_image = models.ImageField(upload_to="profile_pics",blank=True, null=True)

    def __str__(self):
        return self.user.username

#messageモデル
class Message(models.Model):
    loggedin_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='loggedin_user', null=True, blank=True)
    friend = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='friend')
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<Message:id=' + str(self.id) + ', ' + \
        self.title + '(' + str(self.pub_date) + ')>'

    class Meta:
        ordering = ('pub_date',)    

chatapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Account, Message
#フォームクラス作成
class AccountForm(forms.ModelForm):
    #パスワード入力：非表示対応
    password = forms.CharField(widget=forms.PasswordInput(),label="パスワード")

    class Meta():
        #ユーザー認証
        model = User
        #フィールド指定
        fields = ('username','email','password')
        labels = {'username':"ユーザーID",'email':"メール", 'password':"パスワード"}

class AddAccountForm(forms.ModelForm):
    class Meta():
        #モデルクラスを指定
        model = Account
        fields = ('last_name','first_name','account_image',)
        labels = {'last_name':"苗字",'first_name':"名前",'account_image':"写真アップロード",}

#メッセージクラス
class MessageForm(forms.ModelForm):
    class Meta():
        model = Message
        fields = ('title','content')
        labels =  {'title':"タイトル",'content':"本文"}

#名前変更のフォーム
class NameChangeForm(forms.ModelForm):
    class Meta():
        model = Account
        fields = ('last_name', 'first_name')
        labels = {'last_name':"苗字",'first_name':"名前"}
#メールアドレス変更フォーム
class EmailChangeForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('email',)
        labels = {'email':'メ-ルアドレス'}
#アイコン変更フォーム
class IconChangeForm(forms.ModelForm):
    class Meta():
        model = Account
        fields = ('account_image',)
        labels = {'account_image':"新しいアイコン"}
#パスワード変更
class PasswordChange(forms.ModelForm):
    class Meta():
        model = User
        fields = ('password',)
        labels = {'password':'新しいパスワード'}

chatapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView #テンプレートタグ
from .forms import AccountForm, AddAccountForm #ユーザーアカウントフォーム

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
#データベースへのアクセス
from .models import Account, Message
from .forms import AccountForm, MessageForm, NameChangeForm, EmailChangeForm, IconChangeForm, PasswordChange

#ログイン
def Login(request):
    # POST
    if request.method == 'POST':
        # フォーム入力のユーザーID・パスワード取得
        ID = request.POST.get('userid')
        Pass = request.POST.get('password')

        # Djangoの認証機能
        user = authenticate(username=ID, password=Pass)

        # ユーザー認証
        if user:
            #ユーザーアクティベート判定
            if user.is_active:
                # ログイン
                login(request,user)
                # ホームページ遷移
                return HttpResponseRedirect(reverse('chatapp:home'))
            else:
                # アカウント利用不可
                return HttpResponse("アカウントが有効ではありません")
        # ユーザー認証失敗
        else:
            return HttpResponse("ログインIDまたはパスワードが間違っています")
    # GET
    else:
        return render(request, 'chatapp/login.html')


#ログアウト
@login_required
def Logout(request):
    logout(request)
    # ログイン画面遷移
    return HttpResponseRedirect(reverse('Login'))



class AccountRegistration(TemplateView):

    def __init__(self):
        self.params = {
        "AccountCreate":False,
        "account_form": AccountForm(),
        "add_account_form":AddAccountForm(),
        }

    #Get処理
    def get(self,request):
        self.params["account_form"] = AccountForm()
        self.params["add_account_form"] = AddAccountForm()
        self.params["AccountCreate"] = False
        return render(request,"chatapp/register.html",context=self.params)

    #Post処理
    def post(self,request):
        self.params["account_form"] = AccountForm(data=request.POST)
        self.params["add_account_form"] = AddAccountForm(data=request.POST)

        #フォーム入力の有効検証
        if self.params["account_form"].is_valid() and self.params["add_account_form"].is_valid():
            # アカウント情報をDB保存
            account = self.params["account_form"].save()
            # パスワードをハッシュ化
            account.set_password(account.password)
            # ハッシュ化パスワード更新
            account.save()

            # 下記追加情報
            # 下記操作のため、コミットなし
            add_account = self.params["add_account_form"].save(commit=False)
            # AccountForm & AddAccountForm 1vs1 紐付け
            add_account.user = account

            # 画像アップロード有無検証
            if 'account_image' in request.FILES:
                add_account.account_image = request.FILES['account_image']

            # モデル保存
            add_account.save()

            # アカウント作成情報更新
            self.params["AccountCreate"] = True

        else:
            # フォームが有効でない場合
            print(self.params["account_form"].errors)

        return render(request,"chatapp/register.html",context=self.params)
@login_required
def home(request):
    user = Account.objects.get(user=request.user)
    data = Account.objects.exclude(id = user.id)
    loggedin_user = Account.objects.get(id = user.id)
    params = {
        'data': data,
        'loggedin_user': loggedin_user,
        "UserID":request.user,
    }
    return render(request, "chatapp/home.html", params)

def message(request, num):
    if (request.method == 'POST'):
        obj = Message()
        message = MessageForm(request.POST)
        if message.is_valid():
            title = message.cleaned_data['title']
            content = message.cleaned_data['content']
            messages = Message(title=title,content=content, friend=Account.objects.get(id=num), loggedin_user=User.objects.get(id=request.user.id))
            messages.save()
            return redirect("chatapp:message", num=num)
    friend=Account.objects.get(id=num)
    data = Message.objects.filter(friend=friend)
    params = {
        'data': data,
        'friend':friend,
        'form': MessageForm(),
        'num': num,
    }
    return render(request, "chatapp/message.html", params)
def setting(request, num):
    user = Account.objects.get(user=request.user)
    data = Account.objects.exclude(id = user.id)
    loggedin_user = Account.objects.get(id = user.id)
    params = {
        'data': data,
        'loggedin_user': loggedin_user,
        "UserID":request.user,
    }
    return render(request, "chatapp/setting.html", params)

def namechange(request, num):
    obj = Account.objects.get(id=num)
    if(request.method == 'POST'):
        name = NameChangeForm(request.POST, instance=obj)
        name.save()
        return redirect('chatapp:setting', num=num)
    params = {
        'id': num,
        'form': NameChangeForm(instance=obj),
    }
    return render(request, 'chatapp/namechange.html', params)
def adresschange(request, num):
    obj = Account.objects.get(id=num)
    if(request.method == 'POST'):
        email = EmailChangeForm(request.POST, instance=obj)
        email.save()
        return redirect('chatapp:setting', num=num)
    params = {
        'id': num,
        'form': EmailChangeForm(instance=obj),
    }
    return render(request, 'chatapp/adresschange.html', params)
def iconchange(request, num):
    obj = Account.objects.get(id=num)
    if(request.method == 'POST'):
        icon = IconChangeForm(request.POST, instance=obj)
        icon.save()
        return redirect('chatapp:setting', num=num)
    params = {
        'id': num,
        'form':IconChangeForm(instance=obj),
    }
    return render(request, 'chatapp/iconchange.html', params)
def password(request, num):
    obj = Account.objects.get(id=num)
    if(request.method == 'POST'):
        pas = PasswordChange(request.POST, instance=obj)
        pas.save()
        return redirect('chatapp:setting', num=num)
    params = {
        'id': num,
        'form': PasswordChange(instance=obj),
    }
    return render(request, 'chatapp/password.html', params)

chatapp/templates/chatapp/adresschange.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>メアド変更</title>
</head>
<body>
    <h1>メールアドレス変更</h1>
      <form method="post">
        {% csrf_token %}
        <table class='table'>
            {{ form.as_table }}
            <tr>
                <th>
                    <td>
                        <input type="submit" onclick="location.href='chatapp/home.html'" value='click' class="btn btn-primary mt-2">
                    </td>
                </th>
            </tr>
        </table>
    </form>
</body>
</body>
</html>

chatapp/templates/chatapp/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>first</title>
</head>
<body>
    <a href="{% url 'register' %}">新規登録</a>
    <a href="{% url 'login' %}">ログイン</a>
</body>
</html>

chatapp/templates/chatapp/home.html
{% load static %}
<!doctype html>
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8">
<title>home</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>

  <tr>
    <td>{{ loggedin_user.last_name }}　さんようこそ！</td>
    <td><a href="{% url 'chatapp:setting' loggedin_user.id %}">アカウント設定はこちら</a></td>
  </tr>


　<h4>お友達一覧</h4> 
<table class="table">
  <tr>
    <th>IMAGES</th>
    <th>LAST NAME</th>
    <th>FIRST NAME</th>
  </tr>
{% for item in data %}
    <tr>
      <td><img src="{{ item.account_image.url }}" style="border-radius:50%; width:50px; height:50px;"/></td>
      <td>{{ item.last_name }}</td>
      <td>{{ item.first_name }}</td>
      <td><a href="{% url 'chatapp:message' item.id %}">トーク画面へ</a></td>
    </tr>
{% endfor %}  
</table>
 <p class="h5 mt-4"> ログアウトは
 <a href="{% url 'chatapp:login' %}">こちら</a>
 </p>
</body>
</html>

chatapp/templates/chatapp/iconchange.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>画像イメージ変更</title>
</head>
<body>
    <h1>画像イメージ変更</h1>
    <form method="post">
        {% csrf_token %}
        <table class='table'>
            {{ form.as_table }}
            <tr>
                <th>
                    <td>
                        <input type="submit" onclick="location.href='chatapp/home.html'" value='click' class="btn btn-primary mt-2">
                    </td>
                </th>
            </tr>
        </table>
    </form>
</body>
</html>

chatapp/templates/chatapp/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
<title>login</title>
</head>
<body class="container">
  <h1 class="display4 text-primary">ログイン</h1>
<div class="home-group">
 <form method="post" action="{{ login }}">
    {% csrf_token %}
    <table class="reg_form">
    <tr>
    <td><label for="userid">ユーザーID:</label></td>
    <td><input type="text" name="userid"></td>
    <td><label for="password">パスワード：</label></td>
    <td><input type="password" name="password"></td>
    </tr>
    </table>

    <input type="submit" class="btn" value="Login">
 </form>
</div>
   <p class="message">アカウントをお持ちですか？：
   <a href="{% url 'chatapp:register' %}">アカウントを作成</a>
   </p>
</body>
</html>

chatapp/templates/chatapp/message.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    <title>talkroom</title>
</head>
<body class="container">
    <h2 class="display-4 text-primary">{{friend.last_name}}さんとトークしよう！</h2>
    <table class="table">
        <tr>
            <th class="py-1">タイトル</th>
            <th class="py-1">本文</th>
            <th class="py-1">日時</th>
        </tr>
{% for item in data %}
        <tr>
            <td class="py-2">{{item.title}}</td>
            <td class="py-2">{{item.content}}</td>
            <td class="py-2">{{item.pub_date}}</td>
        </tr>        
{% endfor %}
    </table>
     <form action="{% url 'chatapp:message' num %}" method="post">
    {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
            <tr><th><td>
                <input type="submit" onclick="location.href='chatapp/message.html'" value='click' class="btn btn-primary mt-2">
            </td></th></tr>
        </table>
    </form>
    <a href="{% url 'chatapp:home' %}">フレンド一覧へ</a>
    <div class='mt-5'></div>
</body>
</html>

chatapp/templates/chatapp/namechange.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>名前変更</title>
</head>
<body>
    <h1>名前変更</h1>
    <form method="post">
        {% csrf_token %}
        <table class='table'>
            {{ form.as_table }}
            <tr>
                <th>
                    <td>
                        <input type="submit" onclick="location.href='chatapp/home.html'" value='click' class="btn btn-primary mt-2">
                    </td>
                </th>
            </tr>
        </table>
    </form>
</body>
</html>

chatapp/templates/chatapp/password.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>パスワード</title>
</head>
<body>
    <h1>パスワード変更</h1>
    <form method="post">
        {% csrf_token %}
        <table class='table'>
            {{ form.as_table }}
            <tr>
                <th>
                    <td>
                        <input type="submit" onclick="location.href='chatapp/home.html'" value='click' class="btn btn-primary mt-2">
                    </td>
                </th>
            </tr>
        </table>
    </form>
</body>
</html>

chatapp/templates/chatapp/register.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
<title>signup</title>
</head>
<body class="container">
<h1 class="display-4 text-primary">新規登録</h1>
 {% if AccountCreate %}
   <h1 class="display-4 text-primary">登録完了!</h1>
   <a href="{% url 'chatapp:login' %}">ログイン画面へ</a>
 {% else %}
   <div class="reg">
   <table class="reg_form">
   <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   {{ account_form.as_table }}
   {{ add_account_form.as_table }}
   <tr><td></td><td>
   <input class="btn" type="submit" name="" value="登録">
   </td></tr>
   </form>
   </table>
   </div>
 {% endif %}
</body>
</html>

chatapp/templates/chatapp/setting.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    <title>設定</title>
</head>
<body>
  <h1 class="display-4 text-primary">ユーザー設定</h1>
  <table class='table'>
    <th>
        <td><a href="{% url 'chatapp:namechange' loggedin_user.id %}">ユーザー名変更</a></td>
        <td><a href="{% url 'chatapp:adresschange' loggedin_user.id %}">メールアドレス変更</a></td>
        <td><a href="{% url 'chatapp:iconchange' loggedin_user.id %}">アイコン変更</a></td>
        <td><a href="{% url 'chatapp:password' loggedin_user.id %}">パスワード変更</a></td>
        <td><a href="{% url 'chatapp:home' %}">戻る</a></td>
    </th>
  </table>
</body>
</html>